---
- name: Install libs for Qt
  apt:
    pkg:
      - libacl1
      - libandroid-json-org-java
      - libaom0
      - libarchive-zip-perl
      - libargs4j-java
      - libasan5
      - libasound2
      - libasound2-data
      - libasound2-dev
      - libasyncns0
      - libatinject-jsr330-api-java
      - libatomic1
      - libattr1
      - libaudit-common
      - libaudit1
      - libavahi-client3
      - libavahi-common-data
      - libavahi-common3
      - libavcodec-dev
      - libavcodec58
      - libavformat-dev
      - libavformat58
      - libavutil-dev
      - libavutil56
      - libbinutils
      - libblkid-dev
      - libblkid1
      - libbluray2
      - libbrotli1
      - libbsd0
      - libbz2-1.0
      - libc-bin
      - libc-dev-bin
      - libc6
      - libc6-dev
      - libcairo2
      - libcap-dev
      - libcap-ng0
      - libcap2
      - libcap2-bin
      - libcc1-0
      - libchromaprint1
      - libclang1-8
      - libclosure-compiler-java
      - libcodec2-0.9
      - libcom-err2
      - libcroco3
      - libcrypt-dev
      - libcrypt1
      - libctf-nobfd0
      - libctf0
      - libcups2
      - libdatrie1
      - libdb5.3
      - libdbus-1-3
      - libdbus-1-dev
      - libdebconfclient0
      - libdebhelper-perl
      - libdouble-conversion3
      - libdpkg-perl
      - libdrm-amdgpu1
      - libdrm-common
      - libdrm-dev
      - libdrm2
      - libedit2
      - libegl-dev
      - libegl-mesa0
      - libegl1
      - libegl1-mesa-dev
      - libelf1
      - libevdev-dev
      - libevdev2
      - libevent-2.1-7
      - libevent-core-2.1-7
      - libevent-dev
      - libevent-extra-2.1-7
      - libevent-openssl-2.1-7
      - libevent-pthreads-2.1-7
      - libexpat1
      - libexpat1-dev
      - libfdisk1
      - libffi-dev
      - libdrm-radeon1
      - libffi7
      - libfile-stripnondeterminism-perl
      - libflac-dev
      - libflac8
      - libfontconfig1
      - libfontconfig1-dev
      - libfontenc1
      - libfreetype-dev
      - libfreetype6
      - libfreetype6-dev
      - libfribidi0
      - libgbm1
      - libgcc-9-dev
      - libgcc1
      - libgcrypt20
      - libgdbm-compat4
      - libgdbm6
      - libgdk-pixbuf2.0-0
      - libgdk-pixbuf2.0-common
      - libgirepository-1.0-1
      - libgl-dev
      - libgl1
      - libgl1-mesa-dev
      - libgl1-mesa-dri
      - libglapi-mesa
      - libgles-dev
      - libgles1
      - libgles2
      - libgles2-mesa-dev
      - libglib2.0-0
      - libglib2.0-bin
      - libglib2.0-data
      - libglib2.0-dev
      - libglib2.0-dev-bin
      - libglvnd-dev
      - libglvnd0
      - libglx-dev
      - libglx-mesa0
      - libglx0
      - libgme0
      - libgmp10
      - libgnutls30
      - libgomp1
      - libgpg-error0
      - libgraphite2-3
      - libgraphite2-dev
      - libgsm1
      - libgssapi-krb5-2
      - libgstreamer-gl1.0-0
      - libgstreamer-plugins-base1.0-0
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer1.0-0
      - libgstreamer1.0-dev
      - libguava-java
      - libgudev-1.0-0
      - libharfbuzz-dev
      - libharfbuzz-gobject0
      - libharfbuzz-icu0
      - libharfbuzz0b
      - libhogweed5
      - libhyphen0
      - libice6
      - libicu-dev
      - libidn2-0
      - libinput-bin
      - libinput-dev
      - libinput10
      - libisl22
      - libjargs-java
      - libjbig0
      - libjpeg-dev
      - libjsoncpp-dev
      - libjsoncpp1
      - libjsr305-java
      - libk5crypto3
      - libkeyutils1
      - libkrb5-3
      - libkrb5support0
      - liblcms2-2
      - liblcms2-dev
      - libllvm8
      - libllvm9
      - liblz4-1
      - liblzma5
      - libmagic-mgc
      - libmagic1
      - libminizip-dev
      - libminizip1
      - libmount-dev
      - libmount1
      - libmp3lame0
      - libmpc3
      - libmpdec2
      - libmpfr6
      - libmpg123-0
      - libmtdev-dev
      - libmtdev1
      - libncursesw6
      - libnettle7
      - libnspr4
      - libnspr4-dev
      - libnss3
      - libnss3-dev
      - libogg-dev
      - libogg0
      - libopengl-dev
      - libopengl0
      - libopenjp2-7
      - libopenmpt0
      - libopus-dev
      - libopus0
      - liborc-0.4-0
      - liborc-0.4-dev
      - liborc-0.4-dev-bin
      - libp11-kit0
      - libpam-modules
      - libpam-modules-bin
      - libpam-runtime
      - libpam0g
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpci-dev
      - libpci3
      - libpcre16-3
      - libpcre2-16-0
      - libpcre2-32-0
      - libpcre2-8-0
      - libpcre2-dev
      - libpcre2-posix2
      - libpcre3
      - libpcre3-dev
      - libpcre32-3
      - libpcrecpp0v5
      - libpcsclite1
      - libperl5.30
      - libpipeline1
      - libpixman-1-0
      - libpng-dev
      - libpng16-16
      - libprotobuf-dev
      - libprotobuf-lite17
      - libprotobuf17
      - libprotoc17
      - libpthread-stubs0-dev
      - libpulse-dev
      - libpulse-mainloop-glib0
      - libpulse0
      - libre2-5
      - libre2-dev
      - libreadline8
      - librsvg2-2
      - libseccomp2
      - libselinux1
      - libselinux1-dev
      - libsensors-config
      - libsensors5
      - libsepol1
      - libsepol1-dev
      - libshine3
      - libsigsegv2
      - libsm6
      - libsmartcols1
      - libsnappy-dev
      - libsnappy1v5
      - libsndfile1
      - libsoxr0
      - libspeex1
      - libsqlite3-0
      - libsqlite3-dev
      - libssh-gcrypt-4
      - libssl1.1
      - libstdc++-9-dev
      - libstdc++6
      - libsub-override-perl
      - libswresample-dev
      - libswresample3
      - libsystemd0
      - libtasn1-6
      - libthai-data
      - libthai0
      - libtheora0
      - libtiff5
      - libtinfo5
      - libtinfo6
      - libtool
      - libtwolame0
      - libubsan1
      - libuchardet0
      - libudev-dev
      - libudev1
      - libunistring2
      - libcups2-dev
      - libunwind8
      - libusb-1.0-0
      - libusb-1.0-0-dev
      - libuuid1
      - libva-drm2
      - libva-x11-2
      - libva2
      - libvdpau1
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - libvpx-dev
      - libvpx6
      - libvulkan-dev
      - libvulkan1
      - libwacom-common
      - libwacom-dev
      - libwacom2
      - libwavpack1
      - libwayland-client0
      - libwayland-egl1
      - libwayland-server0
      - libwebp-dev
      - libwebp6
      - libwebpdemux2
      - libwebpmux3
      - libwoff1
      - libwrap0
      - libx11-6
      - libx11-data
      - libx11-dev
      - libx11-xcb-dev
      - libx11-xcb1
      - libx264-155
      - libx265-179
      - libxau-dev
      - libxau6
      - libxaw7
      - libxcb-dri2-0
      - libxcb-dri3-0
      - libxcb-glx0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-present0
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-render0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-sync1
      - libxcb-xfixes0
      - libxcb-xinerama0
      - libxcb-xinput0
      - libxcb-xkb1
      - libxcb1
      - libxcb1-dev
      - libxcomposite-dev
      - libxcomposite1
      - libxcursor-dev
      - libxcursor1
      - libxdamage-dev
      - libxdamage1
      - libxdmcp-dev
      - libxdmcp6
      - libxext-dev
      - libxext6
      - libxfixes-dev
      - libxfixes3
      - libxfont2
      - libxi-dev
      - libxi6
      - libxkbcommon-dev
      - libxkbcommon-x11-0
      - libxkbcommon0
      - libxkbfile1
      - libxml2
      - libxml2-dev
      - libxmu6
      - libxmuu1
      - libxnvctrl-dev
      - libxnvctrl0
      - libxpm4
      - libxrandr-dev
      - libxrandr2
      - libxrender-dev
      - libxrender1
      - libxshmfence1
      - libxslt1-dev
      - libxslt1.1
      - libxss-dev
      - libxss1
      - libxt6
      - libxtst-dev
      - libxtst6
      - libxvidcore4
      - libxxf86vm1
      - libyaml-0-2
      - libz3-4
      - libzstd1
      - libzvbi-common
      - libzvbi0
      - linux-libc-dev
      - libssl-dev
      - libsrtp2-dev
      - gettext
      - gettext-base
      - gir1.2-glib-2.0
      - gir1.2-gst-plugins-base-1.0
      - gir1.2-gstreamer-1.0
      - gir1.2-harfbuzz-0.0
      - gperf
      - groff-base
      - gzip
      - hostname
      - icu-devtools
      - init-system-helpers
      - intltool-debian
      - iso-codes
      - java-common
      - java-wrappers
      - khronos-api
      - autoconf
      - automake
      - autopoint
      - autotools-dev
      - base-files
      - base-passwd
      - binutils
      - binutils-arm-linux-gnueabihf
      - binutils-common
      - bison
      - bsdmainutils
      - bsdutils
      - bzip2
      - ca-certificates
      - ca-certificates-java
      - chrpath
      - closure-compiler
      - coreutils
      - dash
      - debconf
      - debhelper
      - debianutils
      - default-jre-headless
      - dh-autoreconf
      - dh-strip-nondeterminism
      - diffutils
      - dpkg
      - dpkg-dev
      - dwz
      - fdisk
      - file
      - findutils
      - flex
      - fontconfig
      - fontconfig-config
      - fonts-dejavu-core
      - gyp
      - login
      - m4
      - mawk
      - mesa-common-dev
      - mime-support
      - ncurses-base
      - ncurses-bin
      - openssl
      - protobuf-compiler

    state: latest
  tags:
    - install_libs_for_qt


- name: Remove build folder Qt 5.15.1
  file:
    path: /tmp/qt_build_5.15.1
    state: absent
  tags:
    - remove_build_folder_qt_5.15.1

      #- name: Remove tar archive Qt 5.15.1
      #  file:
      #      path: /tmp/qt-everywhere-src-5.15.1.tar.xz
      #      state: absent
      #  tags:
      #      remove_qt_5.15.1_archvive

- name: Remove unarchive Qt 5.15.1
  file:
      path: /tmp/qt-everywhere-src-5.15.1
      state: absent
  tags:
      remove_qt_5.15.1_unarchive

- name: Download Qt 5.15.1
  get_url:
    url: http://download.qt.io/official_releases/qt/5.15/5.15.1/single/qt-everywhere-src-5.15.1.tar.xz
    dest: /tmp/qt-everywhere-src-5.15.1.tar.xz
    force: yes
    mode: '0644'
  tags:
    - download_qt_5.15.1 

- name: Unarchive Qt 5.15.1
  unarchive:
    src: /tmp/qt-everywhere-src-5.15.1.tar.xz
    dest: /tmp
    remote_src: yes
  tags:
    - unarchive_qt_5.15.1

- name: Configure Qt 5.15.1
  shell: ./configure -prefix /usr/local -release -platform linux-g++-64 -opensource -confirm-license -make libs -nomake tests -nomake examples -skip qtserialport -system-zlib -system-libjpeg -system-libpng -system-freetype -system-pcre -qt-harfbuzz -glib -fontconfig -sm -opengl -pch -dbus -cups -openssl 
  args:
    chdir: /tmp/qt-everywhere-src-5.15.1
    executable: /bin/bash
  tags:
    - configure_qt_5.15.1

- name: Make all Qt 5.15.1
  shell: make
  args:
    chdir: /tmp/qt-everywhere-src-5.15.1
  tags:
    - make_all_qt_5.15.1

- name: Make install Qt 5.15.1
  make:
    chdir: /tmp/qt-everywhere-src-5.15.1
    target: install
  tags:
    - make_install_qt_5.15.1
