---
- name: Install Docker Dependencies
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
  tags:
    - install_docker_dependencies
